# Generated by Django 4.1.7 on 2023-04-25 04:47

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="CurrencyConverter",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("original_currency", models.CharField(max_length=8)),
                ("target_currency", models.CharField(max_length=8)),
                ("convert_rate", models.DecimalField(decimal_places=2, max_digits=8)),
            ],
            options={
                "verbose_name": "converter",
                "verbose_name_plural": "converter",
            },
        ),
    ]
